addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("nl.gn0s1s" % "sbt-dotenv" % "3.2.0")
addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.28.0")
